# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b3975d0dcc471af70b46d60a3b51d9e0b64d720880acdc39ec5c9c3b4423b5f75028ca1c8acedc905a069b334f33dafe26b52c7f4e37fbc4faf339e9e86dcd7

test:
  secret_key_base: ac90786c42a23f1a2777bd85fb5a32acf288cd8b7c542c7557abf79f584fc1e81100ae20c15718baae7d86da546eefc03df35c4862c2bd88c6ecf39fa926b111

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
